name: Update Checker

env:
  REPO_URL: https://github.com/a0575/padavan
  REPO_BRANCH: master
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * *

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:

    - name: 设置日期
      run: |
        sudo timedatectl set-timezone "$TZ"
        #echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
        echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.workflow_token }}
        event-type: 源码更新

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
